
close_ended: True
seed: 19961103
random_tp_range: 1000
time_limit: 600
fast_reset: False
slow_reset_interval: 9
start_time: 0
origin_resolution: [640, 360]
resize_resolution: [128, 128]

masked_actions: {}


task_conf:
  traj_condition:
    text: "collect wood"
    obs_conf:
      text: "cut down trees for wood"
      ctraj:
        ref_video: "${oc.env:JARVISBASE_TRAJS}/diverses/collect_wood/human/0.mp4"
        ref_mask: "${oc.env:REF_MASK}"
        scale: "(1.0 + (${oc.env:COND_SCALE}))"
      ctraj_sub:
        ref_video: "${oc.env:SUB}"
        ref_mask: "${oc.env:SUB_REF_MASK}"
        scale: "(- ${oc.env:COND_SCALE})"
    reward_conf:
      mine_block: 
        log:
          quantity_rewarded: 100
          reward: 1
          objs:
            - oak_log
            - spruce_log