
close_ended: True
seed: 19961103
random_tp_range: 1000
time_limit: 600
fast_reset: False
slow_reset_interval: 9
start_time: 0
origin_resolution: [640, 360]
resize_resolution: [128, 128]

masked_actions: {}

